### ISSUE TITLE
겜하면서 찾은 미번역/깨지는 이슈들

### ISSUE THREAD

**Issue by Arcanium64** [Translation-Team/DoDKOR#2]
![v2game_2020-10-22_17-48-23](https://user-images.githubusercontent.com/69002441/96848769-ce5cd000-148f-11eb-896b-752e5f39e1e1.png)

디시전 조건문 모든 OR = {}이 ?또는?로 나옴 OR ={ AND = { } }도 마찬가지

![v2game_2020-10-22_17-49-16](https://user-images.githubusercontent.com/69002441/96848088-f0a21e00-148e-11eb-8a14-e4f8b7f11662.png)
이벤트전쟁 언어 깨짐현상

영어로만 출력되는 문화들이 있음(보통 추가문화들) 
찾아서 수정한것들 적어둠
![v2game_2020-10-22_17-56-13](https://user-images.githubusercontent.com/69002441/96848889-ecc2cb80-148f-11eb-93ff-a64bbfedbe45.png)

khanate;칸국;;;;;;;;;;;;;
anglois;앵글로섹슨;;;;;;;;;;;;;
provencal;프로방스;;;;;;;;;;;;;
castilian;카스티야;;;;;;;;;;;;;
zanj;잔지;;;;;;;;;;;;;
nubian;누비아;;;;;;;;;;;;;
khaliji;카리지;;;;;;;;;;;;;
syriac;시리아;;;;;;;;;;;;;
astrakhani;아스트라한;;;;;;;;;;;;;
crimean;크림;;;;;;;;;;;;;
ruthenian;루테니아;;;;;;;;;;;;;
oirat;오이라트;;;;;;;;;;;;;
kalash;케레시;;;;;;;;;;;;;
champa;참파;;;;;;;;;;;;;
acehnese;아체;;;;;;;;;;;;;
venetian;베네치아;;;;;;;;;;;;;
burgundian;부르군트;;;;;;;;;;;;;
rheinish;라인;;;;;;;;;;;;;

![v2game_2020-10-22_17-53-58](https://user-images.githubusercontent.com/69002441/96848613-98b7e700-148f-11eb-8732-69e07d37f8d5.png)

로그 언어 깨짐 현상

![v2game_2020-10-22_17-57-25](https://user-images.githubusercontent.com/69002441/96849038-17148900-1490-11eb-88b7-9f2c5901e7f7.png)

부르군트 PROV2636 깨짐현상

깃헙 10월 21일 오후 8시버전, 원본 그대로 켰음. LUA파일은 HPM 김전일

**Comment by gyhs** [comment]
감사합니다... 센세...

**Comment by gyhs** [comment]
수정 완료
